# Generated by Django 5.1.4 on 2026-02-21 03:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_friends'),
        ('feed', '0001_initial'),
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_focus_skill', models.CharField(blank=True, max_length=50)),
                ('weekly_plan', models.JSONField(blank=True, default=dict)),
                ('skill_sequence', models.JSONField(blank=True, default=list)),
                ('next_challenges', models.JSONField(blank=True, default=list)),
                ('path_version', models.IntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('current_focus_realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.realm')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.5)),
                ('churn_risk', models.FloatField(default=0.5)),
                ('preferred_time_of_day', models.SmallIntegerField(default=12)),
                ('avg_session_length_secs', models.FloatField(default=0.0)),
                ('sessions_per_week', models.FloatField(default=0.0)),
                ('optimal_session_length', models.FloatField(default=900.0)),
                ('personality_cluster', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrimination', models.FloatField(default=1.0, help_text="IRT 'a' parameter")),
                ('difficulty_b', models.FloatField(default=0.0, help_text="IRT 'b' parameter")),
                ('guessing_c', models.FloatField(default=0.25)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_rate', models.FloatField(default=0.5)),
                ('avg_time_secs', models.FloatField(default=0.0)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irt_params', to='realms.challenge')),
            ],
            options={
                'indexes': [models.Index(fields=['difficulty_b'], name='ai_engine_c_difficu_b3721c_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('p_known', models.FloatField(default=0.3)),
                ('p_learn', models.FloatField(default=0.1)),
                ('p_guess', models.FloatField(default=0.25)),
                ('p_slip', models.FloatField(default=0.1)),
                ('observations', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_states', to='accounts.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'skill'], name='ai_engine_k_player__b27c3b_idx')],
                'unique_together': {('player', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=50)),
                ('theta', models.FloatField(default=0.0, help_text='Ability estimate')),
                ('theta_se', models.FloatField(default=1.0, help_text='Standard error')),
                ('responses_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='accounts.player')),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
            options={
                'verbose_name_plural': 'Player abilities',
                'indexes': [models.Index(fields=['player', 'realm'], name='ai_engine_p_player__2d7e1a_idx'), models.Index(fields=['player', 'skill'], name='ai_engine_p_player__78689f_idx')],
                'unique_together': {('player', 'realm', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.FloatField(default=0.0)),
                ('challenges_attempted', models.IntegerField(default=0)),
                ('challenges_correct', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('response_time_variance', models.FloatField(default=0.0)),
                ('realms_visited', models.JSONField(blank=True, default=list)),
                ('abandoned', models.BooleanField(default=False)),
                ('inferred_emotion', models.CharField(blank=True, max_length=30)),
                ('flow_score', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='accounts.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', '-started_at'], name='ai_engine_p_player__4a7a02_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_source', models.CharField(max_length=30)),
                ('score', models.FloatField(default=0.0)),
                ('was_attempted', models.BooleanField(default=False)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('engagement_time_secs', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realms.challenge')),
                ('feed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feeditem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='accounts.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', '-created_at'], name='ai_engine_r_player__a15a9b_idx'), models.Index(fields=['recommendation_source'], name='ai_engine_r_recomme_9acf98_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability', models.FloatField(default=1.0)),
                ('difficulty_fsrs', models.FloatField(default=0.3)),
                ('elapsed_days', models.FloatField(default=0.0)),
                ('scheduled_days', models.FloatField(default=1.0)),
                ('reps', models.IntegerField(default=0)),
                ('lapses', models.IntegerField(default=0)),
                ('state', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=0, help_text='0=new, 1=learning, 2=review, 3=relearning')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='accounts.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'due_date'], name='ai_engine_s_player__65a566_idx'), models.Index(fields=['due_date'], name='ai_engine_s_due_dat_8c3daf_idx')],
                'unique_together': {('player', 'challenge')},
            },
        ),
    ]
