# Generated by Django 5.1.2 on 2026-02-20 16:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color_primary', models.CharField(max_length=7)),
                ('color_secondary', models.CharField(max_length=7)),
                ('unlock_level', models.IntegerField(default=1)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('primary_trait', models.CharField(max_length=30)),
                ('secondary_trait', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('quest_type', models.CharField(choices=[('main', 'Main Quest'), ('side', 'Side Quest'), ('daily', 'Daily Quest'), ('weekly', 'Weekly Quest')], default='main', max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
                ('required_realm_level', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
                ('stat_reward', models.JSONField(blank=True, default=dict)),
                ('intro_dialogue', models.JSONField(blank=True, default=list)),
                ('outro_dialogue', models.JSONField(blank=True, default=list)),
                ('world_position', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisite_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.quest')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='realms.realm')),
            ],
            options={
                'ordering': ['realm', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('challenge_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('pattern_match', 'Pattern Match'), ('sequence', 'Sequence'), ('spatial_puzzle', 'Spatial Puzzle'), ('timed_response', 'Timed Response'), ('scenario_choice', 'Scenario Choice'), ('math_logic', 'Math Logic'), ('emotional_scenario', 'Emotional Scenario'), ('creative_prompt', 'Creative Prompt'), ('memory_test', 'Memory Test'), ('debate_analysis', 'Debate Analysis'), ('financial_decision', 'Financial Decision'), ('word_puzzle', 'Word Puzzle')], max_length=30)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('content', models.JSONField()),
                ('difficulty', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('primary_trait', models.CharField(max_length=30)),
                ('secondary_trait', models.CharField(blank=True, max_length=30)),
                ('trait_points', models.JSONField(blank=True, default=dict)),
                ('time_limit_secs', models.IntegerField(blank=True, null=True)),
                ('base_xp', models.IntegerField(default=10)),
                ('bonus_xp', models.IntegerField(default=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('scene_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='realms.quest')),
            ],
            options={
                'ordering': ['quest', 'sort_order'],
                'indexes': [models.Index(fields=['challenge_type'], name='realms_chal_challen_27e7ff_idx'), models.Index(fields=['difficulty'], name='realms_chal_difficu_e98462_idx'), models.Index(fields=['primary_trait'], name='realms_chal_primary_894fdc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['realm', 'sort_order'], name='realms_ques_realm_i_a26a82_idx'),
        ),
    ]
