# Generated by Django 5.1.2 on 2026-02-20 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('avatar_preset', models.CharField(default='default', max_length=30)),
                ('avatar_colors', models.JSONField(blank=True, default=dict)),
                ('overall_level', models.IntegerField(default=1)),
                ('total_xp', models.BigIntegerField(default=0)),
                ('premium_tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('preferred_lang', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('onboarding_done', models.BooleanField(default=False)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='CompanionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warmth', models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('directness', models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('humor', models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('formality', models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('challenge_level', models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('known_strengths', models.JSONField(blank=True, default=list)),
                ('known_weaknesses', models.JSONField(blank=True, default=list)),
                ('player_preferences', models.JSONField(blank=True, default=dict)),
                ('interaction_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_profile', to='accounts.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-overall_level'], name='accounts_pl_overall_19136b_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-total_xp'], name='accounts_pl_total_x_a5114e_idx'),
        ),
    ]
