# Generated by Django 5.1.2 on 2026-02-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('speed', 'Speed Duel'), ('strategic', 'Strategic Battle'), ('team', 'Team Arena')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerArenaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.IntegerField(default=1000)),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_stats', to='accounts.player')),
            ],
            options={
                'verbose_name_plural': 'Player arena stats',
            },
        ),
    ]
