# Generated by Django 5.1.2 on 2026-02-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('requirement_type', models.CharField(max_length=30)),
                ('requirement_value', models.IntegerField(default=1)),
                ('xp_reward', models.IntegerField(default=50)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='accounts.player')),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.realm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progression.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.player')),
            ],
            options={
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='PlayerChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('time_taken_secs', models.FloatField()),
                ('answer_data', models.JSONField(default=dict)),
                ('xp_earned', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_results', to='accounts.player')),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['player', 'challenge'], name='progression_player__189de3_idx'), models.Index(fields=['played_at'], name='progression_played__ea7b78_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('challenges_total', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to='accounts.player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.quest')),
            ],
            options={
                'unique_together': {('player', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRealmStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_level', models.IntegerField(default=1)),
                ('realm_xp', models.BigIntegerField(default=0)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('challenges_perfect', models.IntegerField(default=0)),
                ('quests_completed', models.IntegerField(default=0)),
                ('visual_stage', models.SmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realm_stats', to='accounts.player')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
            options={
                'ordering': ['realm__sort_order'],
                'indexes': [models.Index(fields=['player', 'realm'], name='progression_player__8e12ba_idx')],
                'unique_together': {('player', 'realm')},
            },
        ),
    ]
