# Generated by Django 5.1.2 on 2026-02-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['category', 'slug']},
        ),
    ]
