# Generated by Django 5.1.2 on 2026-02-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.FloatField(default=50)),
                ('conscientiousness', models.FloatField(default=50)),
                ('extraversion', models.FloatField(default=50)),
                ('agreeableness', models.FloatField(default=50)),
                ('neuroticism', models.FloatField(default=50)),
                ('self_awareness', models.FloatField(default=50)),
                ('empathy', models.FloatField(default=50)),
                ('emotional_regulation', models.FloatField(default=50)),
                ('social_skills', models.FloatField(default=50)),
                ('analytical_thinking', models.FloatField(default=50)),
                ('creative_thinking', models.FloatField(default=50)),
                ('practical_thinking', models.FloatField(default=50)),
                ('risk_tolerance', models.FloatField(default=50)),
                ('learning_style', models.CharField(default='mixed', max_length=20)),
                ('raw_answers', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='accounts.player')),
            ],
        ),
    ]
