# Generated by Django 5.1.2 on 2026-02-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('content_type', models.CharField(choices=[('tip', 'Quick Tip'), ('fact', 'Interesting Fact'), ('challenge', 'Mini Challenge'), ('quote', 'Motivational Quote'), ('lesson', 'Micro Lesson'), ('reflection', 'Reflection Prompt')], max_length=20)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('difficulty', models.SmallIntegerField(default=1)),
                ('xp_value', models.IntegerField(default=5)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='realms.realm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=True)),
                ('liked', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_interactions', to='accounts.player')),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feeditem')),
            ],
            options={
                'unique_together': {('player', 'feed_item')},
            },
        ),
    ]
